-- Down migration: remove PASSWORD_RESET_TOKENS table

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PASSWORD_RESET_TOKENS')
BEGIN
    DROP INDEX IX_PASSWORD_RESET_TOKENS_TOKEN_HASH ON dbo.PASSWORD_RESET_TOKENS;
    DROP INDEX IX_PASSWORD_RESET_TOKENS_USER_ID ON dbo.PASSWORD_RESET_TOKENS;
    DROP TABLE dbo.PASSWORD_RESET_TOKENS;
END
