-- Down migration: remove SQPR supplier/attention columns

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SQPR' AND COLUMN_NAME = 'supplier_id')
BEGIN
    ALTER TABLE [dbo].[SQPR] DROP COLUMN [supplier_id];
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SQPR' AND COLUMN_NAME = 'attention_id')
BEGIN
    ALTER TABLE [dbo].[SQPR] DROP COLUMN [attention_id];
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SQPR' AND COLUMN_NAME = 'attention')
BEGIN
    ALTER TABLE [dbo].[SQPR] DROP COLUMN [attention];
END
