-- Down migration: remove SSI tables in reverse dependency order

IF OBJECT_ID('dbo.SSI_WORKFLOW_EVENT', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.SSI_WORKFLOW_EVENT;
END
GO

IF OBJECT_ID('dbo.SSI_RESPONSE', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.SSI_RESPONSE;
END
GO

IF OBJECT_ID('dbo.SSI_RECORD', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.SSI_RECORD;
END
GO

IF OBJECT_ID('dbo.SSI_PLAN', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.SSI_PLAN;
END
GO
