-- Down migration: remove 8D issuance fields from MNR_LOTS

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'MNR_LOTS' AND COLUMN_NAME = 'report_issuance_8d'
)
BEGIN
    ALTER TABLE MNR_LOTS DROP CONSTRAINT DF_MNR_LOTS_report_issuance_8d;
    ALTER TABLE MNR_LOTS DROP COLUMN report_issuance_8d;
END

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'MNR_LOTS' AND COLUMN_NAME = 'recurrence_ref'
)
BEGIN
    ALTER TABLE MNR_LOTS DROP COLUMN recurrence_ref;
END
