import { escapeEmailHtml, renderBrandedEmailLayout } from './branded-layout.template.js';

export interface AccountVerificationTemplateInput {
  fullName: string;
  email: string;
  verificationUrl: string;
}

export interface RenderedTemplate {
  subject: string;
  html: string;
  text: string;
}

export function buildAccountVerificationTemplate(input: AccountVerificationTemplateInput): RenderedTemplate {
  const subject = 'SQM Account Verification';
  const fullName = escapeEmailHtml(input.fullName);
  const email = escapeEmailHtml(input.email);
  const verificationUrl = escapeEmailHtml(input.verificationUrl);

  const bodyHtml = `
    <div style="padding:0 0 16px 0;color:#202124;font-size:14px;line-height:1.8;">
      Please verify your Toshiba Global SQM account using the link below.
    </div>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;background-color:#ffffff;border:1px solid #e8eaed;margin:8px 0 16px 0;">
      <tr>
        <td style="padding:18px 22px;background-color:#fafafa;color:#202124;font-size:13px;font-weight:700;letter-spacing:0.6px;text-transform:uppercase;border-bottom:1px solid #e8eaed;">
          Verification Details
        </td>
      </tr>
      <tr>
        <td style="padding:14px 22px;color:#202124;font-size:14px;line-height:1.8;">
          <div><strong>Name:</strong> ${fullName}</div>
          <div><strong>Email:</strong> ${email}</div>
          <div><strong>Verification Link:</strong> <a href="${verificationUrl}" target="_blank" style="color:#e60012;text-decoration:none;">${verificationUrl}</a></div>
        </td>
      </tr>
    </table>
  `;

  return {
    subject,
    html: renderBrandedEmailLayout({
      preheader: 'Verify your Toshiba Global SQM account.',
      title: subject,
      greeting: `Dear ${input.fullName},`,
      intro: ['Please verify your Toshiba Global SQM account before signing in.'],
      bodyHtml,
    }),
    text: [
      `Dear ${input.fullName},`,
      '',
      'Please verify your Toshiba Global SQM account before signing in.',
      '',
      `Email: ${input.email}`,
      `Verification Link: ${input.verificationUrl}`,
      '',
      'Note: This email was autogenerated. Please do not reply.',
      '',
      'Very truly yours,',
      'TIP SQM Admin',
    ].join('\n'),
  };
}
