import { escapeEmailHtml, renderBrandedEmailLayout } from './branded-layout.template.js';

function renderDetailRow(label: string, value: string): string {
  return `<tr>
    <td style="padding:10px 0;color:#5f6368;font-size:13px;width:180px;border-bottom:1px solid #e8eaed;">${label}</td>
    <td style="padding:10px 0;color:#202124;font-size:14px;font-weight:600;border-bottom:1px solid #e8eaed;">${value}</td>
  </tr>`;
}

export interface AccountCreatedTemplateInput {
  fullName: string;
  email: string;
  temporaryPassword: string;
  localUrl: string;
  internetUrl: string;
  roleName?: string | null;
  siteId?: string | null;
}

export interface RenderedTemplate {
  subject: string;
  html: string;
  text: string;
}

export function buildAccountCreatedTemplate(input: AccountCreatedTemplateInput): RenderedTemplate {
  const fullName = escapeEmailHtml(input.fullName);
  const email = escapeEmailHtml(input.email);
  const temporaryPassword = escapeEmailHtml(input.temporaryPassword);
  const localUrl = escapeEmailHtml(input.localUrl);
  const internetUrl = escapeEmailHtml(input.internetUrl);

  const subject = 'Account Confirmation';

  const bodyHtml = `
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;background-color:#ffffff;border:1px solid #e8eaed;margin:8px 0 16px 0;">
      <tr>
        <td style="padding:18px 22px;background-color:#fafafa;color:#202124;font-size:13px;font-weight:700;letter-spacing:0.6px;text-transform:uppercase;border-bottom:1px solid #e8eaed;">
          Account Details
        </td>
      </tr>
      <tr>
        <td style="padding:0 22px 8px 22px;">
          <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;">
            ${renderDetailRow('Name', fullName)}
            ${renderDetailRow('Email', email)}
            ${renderDetailRow('Username', email)}
            ${renderDetailRow('Temporary Password', temporaryPassword)}
          </table>
        </td>
      </tr>
    </table>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;">
      <tr>
        <td style="padding:0 0 10px 0;color:#5f6368;font-size:12px;font-weight:700;letter-spacing:0.6px;text-transform:uppercase;">
          Access Links
        </td>
      </tr>
      <tr>
        <td style="padding:0 0 12px 0;">
          <a href="${internetUrl}" target="_blank" style="display:inline-block;background-color:#e60012;color:#ffffff;text-decoration:none;font-size:14px;font-weight:700;padding:12px 22px;border-radius:2px;">Open SQM Web</a>
        </td>
      </tr>
      <tr>
        <td style="padding:0 0 10px 0;color:#5f6368;font-size:13px;line-height:1.7;">
          Web Link: <a href="${internetUrl}" target="_blank" style="color:#e60012;text-decoration:none;">${internetUrl}</a>
        </td>
      </tr>
      <tr>
        <td style="padding:0;color:#5f6368;font-size:13px;line-height:1.7;">
          Local Link: <a href="${localUrl}" target="_blank" style="color:#e60012;text-decoration:none;">${localUrl}</a>
        </td>
      </tr>
    </table>
  `;

  const html = renderBrandedEmailLayout({
    preheader: 'Your Toshiba Global SQM account has been confirmed.',
    title: subject,
    greeting: `Dear ${input.fullName},`,
    intro: [
      'Welcome to Toshiba Global SQM (Supplier Quality Management).',
      'Your account has been confirmed. If you skip to change your password you are still require to change when you login. Please use temporay password to login to SQM.',
    ],
    bodyHtml,
  });

  const textLines = [
    `Dear ${input.fullName},`,
    '',
    'Welcome to Toshiba Global SQM (Supplier Quality Management).',
    'Your account has been confirmed. If you skip to change your password you are still require to change when you login. Please use temporay password to login to SQM.',
    '',
    `Web Link: ${input.internetUrl}`,
    `Local Link: ${input.localUrl}`,
    '',
    `Name: ${input.fullName}`,
    `Email: ${input.email}`,
    `Username: ${input.email}`,
    `Temporary Password: ${input.temporaryPassword}`,
    '',
    'Note: This email was autogenerated. Please do not reply.',
    '',
    'Very truly yours,',
    'TIP SQM Admin',
  ].filter((line): line is string => Boolean(line));

  return {
    subject,
    html,
    text: textLines.join('\n'),
  };
}
