function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export interface BrandedEmailLayoutInput {
  preheader: string;
  title: string;
  greeting?: string;
  intro?: string[];
  bodyHtml: string;
  footerNote?: string;
  signoffName?: string;
  supportLabel?: string;
}

export function escapeEmailHtml(value: string): string {
  return escapeHtml(value);
}

export function renderBrandedEmailLayout(input: BrandedEmailLayoutInput): string {
  const greeting = input.greeting ? `<div style="font-size:14px;line-height:1.7;color:#5f6368;">${escapeHtml(input.greeting)}</div>` : '';
  const introHtml = (input.intro || [])
    .map((paragraph) => `<p style="margin:0 0 16px 0;">${escapeHtml(paragraph)}</p>`)
    .join('');
  const footerNote = input.footerNote || 'Note: This email was autogenerated. Please do not reply.';
  const signoffName = input.signoffName || 'TIP SQM Admin';
  const supportLabel = input.supportLabel || 'Toshiba Global SQM notification service';

  return `<div style="margin:0;padding:0;background-color:#f5f5f5;">
  <div style="display:none;font-size:1px;color:#f5f5f5;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">
    ${escapeHtml(input.preheader)}
  </div>
  <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background-color:#f5f5f5;margin:0;padding:24px 0;font-family:Arial,Helvetica,sans-serif;">
    <tr>
      <td align="center">
        <table role="presentation" cellpadding="0" cellspacing="0" width="640" style="width:640px;max-width:640px;background-color:#ffffff;border-collapse:collapse;border:1px solid #dadce0;">
          <tr>
            <td style="padding:0;background-color:#e60012;">
              <table role="presentation" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td style="padding:18px 28px;color:#ffffff;font-size:28px;font-weight:700;letter-spacing:1px;">
                    TOSHIBA
                  </td>
                  <td align="right" style="padding:18px 28px;color:#ffd9dd;font-size:12px;letter-spacing:1.2px;text-transform:uppercase;">
                    Supplier Quality Management
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr>
            <td style="padding:32px 36px 12px 36px;color:#202124;">
              <div style="font-size:24px;font-weight:700;line-height:1.3;margin-bottom:8px;">${escapeHtml(input.title)}</div>
              ${greeting}
            </td>
          </tr>
          <tr>
            <td style="padding:0 36px 8px 36px;color:#202124;font-size:14px;line-height:1.8;">
              ${introHtml}
            </td>
          </tr>
          <tr>
            <td style="padding:0 36px 0 36px;color:#202124;font-size:14px;line-height:1.8;">
              ${input.bodyHtml}
            </td>
          </tr>
          <tr>
            <td style="padding:18px 36px 14px 36px;color:#202124;font-size:13px;line-height:1.8;">
              <div style="padding:14px 16px;background-color:#fafafa;border-left:4px solid #e60012;color:#5f6368;">
                ${escapeHtml(footerNote)}
              </div>
            </td>
          </tr>
          <tr>
            <td style="padding:0 36px 32px 36px;color:#5f6368;font-size:13px;line-height:1.8;">
              Very truly yours,<br />
              <span style="color:#202124;font-weight:700;">${escapeHtml(signoffName)}</span>
            </td>
          </tr>
          <tr>
            <td style="padding:14px 36px;background-color:#f1f3f4;color:#5f6368;font-size:11px;line-height:1.6;border-top:1px solid #e8eaed;">
              ${escapeHtml(supportLabel)}
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</div>`;
}
