import { escapeEmailHtml, renderBrandedEmailLayout } from './branded-layout.template.js';

export interface FiveM1ENotificationTemplateInput {
  subject: string;
  title: string;
  message: string;
  controlNo: string;
  requestTitle?: string | null;
  supplierName?: string | null;
  siteName?: string | null;
  actorName?: string | null;
  pic: string;
  action: string;
  localUrl: string;
  internetUrl: string;
}

export interface RenderedTemplate {
  subject: string;
  html: string;
  text: string;
}

export function buildFiveM1ENotificationTemplate(
  input: FiveM1ENotificationTemplateInput,
): RenderedTemplate {
  const safeSubject = escapeEmailHtml(input.subject);
  const safeMessage = escapeEmailHtml(input.message);
  const safeControlNo = escapeEmailHtml(input.controlNo);
  const safeRequestTitle = escapeEmailHtml(input.requestTitle || '-');
  const safeSupplierName = escapeEmailHtml(input.supplierName || '-');
  const safeSiteName = escapeEmailHtml(input.siteName || '-');
  const safeActorName = escapeEmailHtml(input.actorName || '-');
  const safePic = escapeEmailHtml(input.pic);
  const safeAction = escapeEmailHtml(input.action);
  const safeLocalUrl = escapeEmailHtml(input.localUrl);
  const safeInternetUrl = escapeEmailHtml(input.internetUrl);

  const bodyHtml = `
    <div style="margin-bottom:16px;">${safeMessage}</div>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;margin:8px 0 20px 0;">
      <tr>
        <td style="padding:12px 14px;background:#fafafa;border:1px solid #e8eaed;font-size:14px;line-height:1.8;">
          <div><strong>Control No.:</strong> ${safeControlNo}</div>
          <div><strong>Title:</strong> ${safeRequestTitle}</div>
          <div><strong>Supplier:</strong> ${safeSupplierName}</div>
          <div><strong>Site:</strong> ${safeSiteName}</div>
          <div><strong>Actor:</strong> ${safeActorName}</div>
          <div><strong>Legacy PIC:</strong> ${safePic}</div>
          <div><strong>Legacy Action:</strong> ${safeAction}</div>
        </td>
      </tr>
    </table>
    <div style="margin-bottom:8px;"><strong>Web Link (URL):</strong> <a href="${safeInternetUrl}" style="color:#0b57d0;">${safeInternetUrl}</a></div>
    <div><strong>Local Link (URL):</strong> <a href="${safeLocalUrl}" style="color:#0b57d0;">${safeLocalUrl}</a></div>
  `;

  return {
    subject: input.subject,
    html: renderBrandedEmailLayout({
      preheader: input.subject,
      title: input.title,
      greeting: 'Please review the latest 5M1E workflow activity.',
      intro: [
        'A 5M1E application has advanced in workflow.',
      ],
      bodyHtml,
      footerNote: 'Note: This email was autogenerated. Please do not reply.',
      signoffName: 'TIP SQM Admin',
      supportLabel: 'Toshiba Global SQM 5M1E notification service',
    }),
    text: [
      safeSubject,
      '',
      safeMessage,
      `Control No.: ${input.controlNo}`,
      `Title: ${input.requestTitle || '-'}`,
      `Supplier: ${input.supplierName || '-'}`,
      `Site: ${input.siteName || '-'}`,
      `Actor: ${input.actorName || '-'}`,
      `Legacy PIC: ${input.pic}`,
      `Legacy Action: ${input.action}`,
      `Web Link (URL): ${input.internetUrl}`,
      `Local Link (URL): ${input.localUrl}`,
      '',
      'Note: This email was autogenerated. Please do not reply.',
    ].join('\n'),
  };
}
