import { escapeEmailHtml, renderBrandedEmailLayout } from './branded-layout.template.js';

export interface PasswordResetRequestTemplateInput {
  fullName: string;
  email: string;
  resetUrl: string;
  expiresInMinutes?: number;
}

export interface RenderedTemplate {
  subject: string;
  html: string;
  text: string;
}

export function buildPasswordResetRequestTemplate(
  input: PasswordResetRequestTemplateInput,
): RenderedTemplate {
  const subject = 'Reset Your SQM Password';
  const fullName = escapeEmailHtml(input.fullName);
  const email = escapeEmailHtml(input.email);
  const resetUrl = escapeEmailHtml(input.resetUrl);
  const expiresInMinutes = input.expiresInMinutes ?? 30;

  const bodyHtml = `
    <div style="padding:0 0 16px 0;color:#202124;font-size:14px;line-height:1.8;">
      We received a request to reset the SQM password for the account below.
    </div>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;background-color:#ffffff;border:1px solid #e8eaed;margin:8px 0 16px 0;">
      <tr>
        <td style="padding:18px 22px;background-color:#fafafa;color:#202124;font-size:13px;font-weight:700;letter-spacing:0.6px;text-transform:uppercase;border-bottom:1px solid #e8eaed;">
          Password Reset
        </td>
      </tr>
      <tr>
        <td style="padding:14px 22px;color:#202124;font-size:14px;line-height:1.8;">
          <div><strong>Name:</strong> ${fullName}</div>
          <div><strong>Email:</strong> ${email}</div>
          <div><strong>Reset Link:</strong> <a href="${resetUrl}" target="_blank" style="color:#e60012;text-decoration:none;">${resetUrl}</a></div>
          <div><strong>Expires In:</strong> ${expiresInMinutes} minutes</div>
        </td>
      </tr>
    </table>
  `;

  return {
    subject,
    html: renderBrandedEmailLayout({
      preheader: 'A password reset was requested for your SQM account.',
      title: subject,
      greeting: `Dear ${input.fullName},`,
      intro: [
        'Use the reset link below to create a new password for your Toshiba Global SQM account.',
        'If you did not request this change, ignore this email.',
      ],
      bodyHtml,
    }),
    text: [
      `Dear ${input.fullName},`,
      '',
      'Use the reset link below to create a new password for your Toshiba Global SQM account.',
      'If you did not request this change, ignore this email.',
      '',
      `Email: ${input.email}`,
      `Reset Link: ${input.resetUrl}`,
      `Expires In: ${expiresInMinutes} minutes`,
      '',
      'Note: This email was autogenerated. Please do not reply.',
      '',
      'Very truly yours,',
      'TIP SQM Admin',
    ].join('\n'),
  };
}
