import { escapeEmailHtml, renderBrandedEmailLayout } from './branded-layout.template.js';

export interface PasswordChangedTemplateInput {
  fullName: string;
  email: string;
  localUrl: string;
  internetUrl: string;
}

export interface RenderedTemplate {
  subject: string;
  html: string;
  text: string;
}

export function buildPasswordChangedTemplate(input: PasswordChangedTemplateInput): RenderedTemplate {
  const subject = 'Password Change Confirmation';
  const fullName = escapeEmailHtml(input.fullName);
  const email = escapeEmailHtml(input.email);
  const localUrl = escapeEmailHtml(input.localUrl);
  const internetUrl = escapeEmailHtml(input.internetUrl);

  const bodyHtml = `
    <div style="padding:0 0 16px 0;color:#202124;font-size:14px;line-height:1.8;">
      Your SQM password was updated successfully. If you did not perform this change, contact the SQM administrator immediately.
    </div>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;background-color:#ffffff;border:1px solid #e8eaed;margin:8px 0 16px 0;">
      <tr>
        <td style="padding:18px 22px;background-color:#fafafa;color:#202124;font-size:13px;font-weight:700;letter-spacing:0.6px;text-transform:uppercase;border-bottom:1px solid #e8eaed;">
          Account Details
        </td>
      </tr>
      <tr>
        <td style="padding:14px 22px;color:#202124;font-size:14px;line-height:1.8;">
          <div><strong>Name:</strong> ${fullName}</div>
          <div><strong>Email:</strong> ${email}</div>
        </td>
      </tr>
    </table>
    <div style="padding:0 0 10px 0;color:#5f6368;font-size:12px;font-weight:700;letter-spacing:0.6px;text-transform:uppercase;">
      Access Links
    </div>
    <div style="padding:0 0 10px 0;color:#5f6368;font-size:13px;line-height:1.7;">
      Web Link: <a href="${internetUrl}" target="_blank" style="color:#e60012;text-decoration:none;">${internetUrl}</a>
    </div>
    <div style="padding:0;color:#5f6368;font-size:13px;line-height:1.7;">
      Local Link: <a href="${localUrl}" target="_blank" style="color:#e60012;text-decoration:none;">${localUrl}</a>
    </div>
  `;

  return {
    subject,
    html: renderBrandedEmailLayout({
      preheader: 'Your SQM password has been changed.',
      title: subject,
      greeting: `Dear ${input.fullName},`,
      intro: ['This is a confirmation that your Toshiba Global SQM password has been changed.'],
      bodyHtml,
    }),
    text: [
      `Dear ${input.fullName},`,
      '',
      'This is a confirmation that your Toshiba Global SQM password has been changed.',
      'If you did not perform this change, contact the SQM administrator immediately.',
      '',
      `Email: ${input.email}`,
      `Web Link: ${input.internetUrl}`,
      `Local Link: ${input.localUrl}`,
      '',
      'Note: This email was autogenerated. Please do not reply.',
      '',
      'Very truly yours,',
      'TIP SQM Admin',
    ].join('\n'),
  };
}
