import { escapeEmailHtml, renderBrandedEmailLayout } from './branded-layout.template.js';

export interface SqprNotificationTemplateInput {
  subject: string;
  message: string;
  controlNo: string;
  supplierName: string;
  periodLabel: string;
  localUrl: string;
  internetUrl: string;
}

export interface RenderedTemplate {
  subject: string;
  html: string;
  text: string;
}

function renderDetailRow(label: string, value: string): string {
  return `<tr>
    <td style="padding:10px 0;color:#5f6368;font-size:13px;width:160px;border-bottom:1px solid #e8eaed;">${label}</td>
    <td style="padding:10px 0;color:#202124;font-size:14px;font-weight:600;border-bottom:1px solid #e8eaed;">${value}</td>
  </tr>`;
}

export function buildSqprNotificationTemplate(input: SqprNotificationTemplateInput): RenderedTemplate {
  const safeMessage = escapeEmailHtml(input.message);
  const safeControlNo = escapeEmailHtml(input.controlNo);
  const safeSupplierName = escapeEmailHtml(input.supplierName);
  const safePeriodLabel = escapeEmailHtml(input.periodLabel);
  const safeLocalUrl = escapeEmailHtml(input.localUrl);
  const safeInternetUrl = escapeEmailHtml(input.internetUrl);

  const bodyHtml = `
    <div style="padding:18px 20px;background-color:#fafafa;border:1px solid #e8eaed;margin:8px 0 18px 0;color:#202124;font-size:14px;line-height:1.8;">
      <strong style="display:block;font-size:13px;letter-spacing:0.6px;text-transform:uppercase;color:#5f6368;margin-bottom:8px;">Workflow Update</strong>
      ${safeMessage}
    </div>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;background-color:#ffffff;border:1px solid #e8eaed;margin:0 0 16px 0;">
      <tr>
        <td style="padding:18px 22px;background-color:#fafafa;color:#202124;font-size:13px;font-weight:700;letter-spacing:0.6px;text-transform:uppercase;border-bottom:1px solid #e8eaed;">
          Supplier Quality Performance Rating Report
        </td>
      </tr>
      <tr>
        <td style="padding:0 22px 8px 22px;">
          <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;">
            ${renderDetailRow('Control No', safeControlNo)}
            ${renderDetailRow('Supplier', safeSupplierName)}
            ${renderDetailRow('Period', safePeriodLabel)}
          </table>
        </td>
      </tr>
    </table>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;">
      <tr>
        <td style="padding:0 0 12px 0;">
          <a href="${safeInternetUrl}" target="_blank" style="display:inline-block;background-color:#e60012;color:#ffffff;text-decoration:none;font-size:14px;font-weight:700;padding:12px 22px;border-radius:2px;">Open SQPR Record</a>
        </td>
      </tr>
      <tr>
        <td style="padding:0 0 10px 0;color:#5f6368;font-size:13px;line-height:1.7;">
          Local Link: <a href="${safeLocalUrl}" target="_blank" style="color:#e60012;text-decoration:none;">${safeLocalUrl}</a>
        </td>
      </tr>
      <tr>
        <td style="padding:0;color:#5f6368;font-size:13px;line-height:1.7;">
          Web Link: <a href="${safeInternetUrl}" target="_blank" style="color:#e60012;text-decoration:none;">${safeInternetUrl}</a>
        </td>
      </tr>
    </table>
  `;

  const html = renderBrandedEmailLayout({
    preheader: `${input.subject} - ${input.controlNo}`,
    title: input.subject,
    intro: ['Supplier Quality Performance Rating Report'],
    bodyHtml,
    supportLabel: 'Toshiba Global SQM notification service',
  });

  const text = [
    'Supplier Quality Performance Rating Report',
    '',
    input.message,
    '',
    `Control No: ${input.controlNo}`,
    `Supplier: ${input.supplierName}`,
    `Period: ${input.periodLabel}`,
    `Local Link: ${input.localUrl}`,
    `Web Link: ${input.internetUrl}`,
    '',
    'Note: This email was autogenerated. Please do not reply.',
    '',
    'Very truly yours,',
    'TIP SQM Admin',
  ].join('\n');

  return {
    subject: input.subject,
    html,
    text,
  };
}
