import { SYSTEM_SITE } from './seed-constants.js';

export const coreMasterReferenceSeed = {
  sites: [
    {
      site_id: SYSTEM_SITE.id,
      site_name: SYSTEM_SITE.name,
      site_code: SYSTEM_SITE.code,
      site_desc: SYSTEM_SITE.description,
    },
    {
      site_id: 'SITE-BKK',
      site_name: 'Bangkok Plant',
      site_code: 'BKK',
      site_desc: 'Main electronics assembly and supplier quality hub',
    },
    {
      site_id: 'SITE-CBR',
      site_name: 'Chonburi Plant',
      site_code: 'CBR',
      site_desc: 'Molding, stamping, and incoming material inspection site',
    },
    {
      site_id: 'SITE-RYG',
      site_name: 'Rayong Plant',
      site_code: 'RYG',
      site_desc: 'Final assembly and audit readiness site',
    },
  ],
  suppliers: [
    {
      supplier_id: 'SUP-ALPHA',
      supplier_name: 'Alpha Electronics Co.',
      site_code: 'BKK',
      location: 'Bangkok, Thailand',
      supplier_desc: 'PCB, controller, and sub-assembly supplier',
    },
    {
      supplier_id: 'SUP-BETA',
      supplier_name: 'Beta Plastics Ltd.',
      site_code: 'CBR',
      location: 'Chonburi, Thailand',
      supplier_desc: 'Plastic housings, reels, and molded fixtures',
    },
    {
      supplier_id: 'SUP-GAMMA',
      supplier_name: 'Gamma Metal Works',
      site_code: 'RYG',
      location: 'Rayong, Thailand',
      supplier_desc: 'Metal brackets, stamped parts, and shielding',
    },
    {
      supplier_id: 'SUP-DELTA',
      supplier_name: 'Delta Cable Systems',
      site_code: 'BKK',
      location: 'Ayutthaya, Thailand',
      supplier_desc: 'Cable assemblies and wire harness subcomponents',
    },
  ],
  products: [
    {
      product_id: 'PROD-ECU',
      product_name: 'Automotive ECU',
      product_code: 'ECU-A100',
      product_desc: 'Electronic control unit platform',
      site_code: 'BKK',
    },
    {
      product_id: 'PROD-HMI',
      product_name: 'Display Assembly',
      product_code: 'DSP-H200',
      product_desc: 'Display and HMI sub-assembly',
      site_code: 'CBR',
    },
    {
      product_id: 'PROD-SNS',
      product_name: 'Sensor Module',
      product_code: 'SNS-R300',
      product_desc: 'Environmental and motion sensing module',
      site_code: 'RYG',
    },
  ],
  models: [
    {
      model_id: 'MOD-ECU-STD',
      model_name: 'ECU Standard',
      model_no: 'ECU-STD-2026',
      model_desc: 'Standard production ECU model',
      product_code: 'ECU-A100',
      site_code: 'BKK',
    },
    {
      model_id: 'MOD-ECU-PRO',
      model_name: 'ECU Premium',
      model_no: 'ECU-PRM-2026',
      model_desc: 'Premium ECU with expanded diagnostics',
      product_code: 'ECU-A100',
      site_code: 'BKK',
    },
    {
      model_id: 'MOD-DSP-LCD',
      model_name: 'Display LCD',
      model_no: 'DSP-LCD-2026',
      model_desc: 'LCD-based HMI assembly',
      product_code: 'DSP-H200',
      site_code: 'CBR',
    },
    {
      model_id: 'MOD-SNS-IMU',
      model_name: 'Sensor IMU',
      model_no: 'SNS-IMU-2026',
      model_desc: 'Inertial sensor module',
      product_code: 'SNS-R300',
      site_code: 'RYG',
    },
  ],
  mfgAreas: [
    {
      mfg_area_id: 'AREA-INCOMING',
      mfg_area_name: 'Incoming Inspection',
      mfg_area_desc: 'Incoming material inspection and release',
    },
    {
      mfg_area_id: 'AREA-ASSY',
      mfg_area_name: 'Assembly Line',
      mfg_area_desc: 'Main line assembly and process verification',
    },
    {
      mfg_area_id: 'AREA-LAB',
      mfg_area_name: 'Testing Laboratory',
      mfg_area_desc: 'Dimensional, functional, and environmental testing',
    },
    {
      mfg_area_id: 'AREA-OQA',
      mfg_area_name: 'Outgoing Quality',
      mfg_area_desc: 'Final inspection, audit, and shipment release',
    },
  ],
};

export const qualityReferenceSeed = {
  defectCategories: [
    {
      defectcategory_id: 'DCAT-APP',
      defectcategory_name: 'Appearance',
      defectcategory_acronym: 'APP',
      defectcategory_desc: 'Visual and cosmetic issues',
    },
    {
      defectcategory_id: 'DCAT-DIM',
      defectcategory_name: 'Dimensional',
      defectcategory_acronym: 'DIM',
      defectcategory_desc: 'Dimensional and tolerance-related issues',
    },
    {
      defectcategory_id: 'DCAT-FUNC',
      defectcategory_name: 'Functional',
      defectcategory_acronym: 'FUN',
      defectcategory_desc: 'Electrical or functional performance issues',
    },
    {
      defectcategory_id: 'DCAT-MATL',
      defectcategory_name: 'Material',
      defectcategory_acronym: 'MAT',
      defectcategory_desc: 'Raw material, contamination, or composition issues',
    },
  ],
  defects: [
    {
      defect_id: 'DEF-SCRATCH',
      defect_name: 'Scratch',
      defect_desc: 'Visible scratch on cosmetic or critical surface',
    },
    {
      defect_id: 'DEF-BURR',
      defect_name: 'Burr',
      defect_desc: 'Sharp edge or residual burr from trimming or stamping',
    },
    {
      defect_id: 'DEF-MISS',
      defect_name: 'Missing Component',
      defect_desc: 'Required component or material not present',
    },
    {
      defect_id: 'DEF-OOS',
      defect_name: 'Out of Specification',
      defect_desc: 'Measured value outside approved tolerance or limit',
    },
    {
      defect_id: 'DEF-CONT',
      defect_name: 'Contamination',
      defect_desc: 'Foreign particle, oil, residue, or dust contamination',
    },
    {
      defect_id: 'DEF-MISALIGN',
      defect_name: 'Misalignment',
      defect_desc: 'Assembly or positioning deviation',
    },
  ],
  defectClasses: [
    {
      defectclass_id: 'DCLS-CRITICAL',
      defectclass_name: 'Critical',
      defectclass_desc: 'Safety or regulatory critical defect',
    },
    {
      defectclass_id: 'DCLS-MAJOR',
      defectclass_name: 'Major',
      defectclass_desc: 'Primary fit, form, or function defect',
    },
    {
      defectclass_id: 'DCLS-MINOR',
      defectclass_name: 'Minor',
      defectclass_desc: 'Cosmetic or low-risk deviation',
    },
  ],
  dispositions: [
    {
      disposition_id: 'DISP-ACCEPT',
      disposition_name: 'Accept',
      disposition_desc: 'Accept product as is',
    },
    {
      disposition_id: 'DISP-REJECT',
      disposition_name: 'Reject',
      disposition_desc: 'Reject and segregate for supplier action',
    },
    {
      disposition_id: 'DISP-REWORK',
      disposition_name: 'Rework',
      disposition_desc: 'Rework and re-inspect before release',
    },
    {
      disposition_id: 'DISP-USEASIS',
      disposition_name: 'Use As Is',
      disposition_desc: 'Use with documented deviation approval',
    },
    {
      disposition_id: 'DISP-RTS',
      disposition_name: 'Return to Supplier',
      disposition_desc: 'Return material to supplier',
    },
  ],
  severities: [
    {
      severity_id: 'SEV-L1',
      severity_name: 'Level I',
      severity_desc: 'Reduced sample severity',
    },
    {
      severity_id: 'SEV-L2',
      severity_name: 'Level II',
      severity_desc: 'Normal sample severity',
    },
    {
      severity_id: 'SEV-L3',
      severity_name: 'Level III',
      severity_desc: 'Tightened sample severity',
    },
    {
      severity_id: 'SEV-SPECIAL',
      severity_name: 'Special',
      severity_desc: 'Special-case or customer-defined severity',
    },
  ],
  mnrTypes: [
    {
      mnrtype_id: 'MNR-MATERIAL',
      mnrtype_name: 'Material Non-Conformance',
      mnrtype_desc: 'Incoming or stock material issue',
    },
    {
      mnrtype_id: 'MNR-PROCESS',
      mnrtype_name: 'Process Non-Conformance',
      mnrtype_desc: 'In-process or work instruction deviation',
    },
    {
      mnrtype_id: 'MNR-PRODUCT',
      mnrtype_name: 'Product Non-Conformance',
      mnrtype_desc: 'Final or shipment-stage product issue',
    },
    {
      mnrtype_id: 'MNR-SUPPLIER',
      mnrtype_name: 'Supplier Issue',
      mnrtype_desc: 'Supplier-originated quality concern',
    },
  ],
};

export const inspectionReferenceSeed = {
  inspectionCategories: [
    {
      inspectioncat_id: 'INSC-INCOMING',
      inspectioncat_name: 'Incoming Inspection',
      inspectioncat_desc: 'Incoming material receiving and release check',
    },
    {
      inspectioncat_id: 'INSC-INPROC',
      inspectioncat_name: 'In-Process Inspection',
      inspectioncat_desc: 'Process and line patrol inspection',
    },
    {
      inspectioncat_id: 'INSC-FINAL',
      inspectioncat_name: 'Final Inspection',
      inspectioncat_desc: 'Final lot release inspection',
    },
    {
      inspectioncat_id: 'INSC-AUDIT',
      inspectioncat_name: 'Audit Inspection',
      inspectioncat_desc: 'Audit or verification sampling inspection',
    },
  ],
  inspectionMethods: [
    {
      inspectionmethod_id: 'INSM-VISUAL',
      inspectionmethod_name: 'Visual Inspection',
      inspectionmethod_desc: 'Visual standard comparison and attribute check',
      default_temp: 25,
      default_hum: 50,
      default_value: 1,
    },
    {
      inspectionmethod_id: 'INSM-DIM',
      inspectionmethod_name: 'Dimensional Check',
      inspectionmethod_desc: 'Caliper, gauge, or CMM dimensional verification',
      default_temp: 23,
      default_hum: 45,
      default_value: 1,
    },
    {
      inspectionmethod_id: 'INSM-FUNC',
      inspectionmethod_name: 'Functional Test',
      inspectionmethod_desc: 'Power-on or functional performance validation',
      default_temp: 25,
      default_hum: 50,
      default_value: 1,
    },
    {
      inspectionmethod_id: 'INSM-ENV',
      inspectionmethod_name: 'Environmental Check',
      inspectionmethod_desc: 'Condition and exposure-based verification',
      default_temp: 30,
      default_hum: 60,
      default_value: 0,
    },
  ],
  inspectors: [
    {
      inspector_id: 'INS-JSMITH',
      inspector_name: 'John Smith',
      inspector_desc: 'Incoming and final inspection lead',
    },
    {
      inspector_id: 'INS-JDOE',
      inspector_name: 'Jane Doe',
      inspector_desc: 'Process quality and layered audit inspector',
    },
    {
      inspector_id: 'INS-MLEE',
      inspector_name: 'Maria Lee',
      inspector_desc: 'Dimensional and calibration laboratory inspector',
    },
    {
      inspector_id: 'INS-DTAN',
      inspector_name: 'Daniel Tan',
      inspector_desc: 'Functional verification and outgoing audit inspector',
    },
  ],
  aqls: [
    {
      aql_id: 'AQL-STD',
      aql_name: 'AQL 1.0/2.5',
      minor: '1.0',
      major: '2.5',
      site_code: 'BKK',
      aql_desc: 'Standard automotive incoming inspection plan',
    },
    {
      aql_id: 'AQL-TIGHT',
      aql_name: 'AQL 0.65/1.0',
      minor: '0.65',
      major: '1.0',
      site_code: 'CBR',
      aql_desc: 'Tightened plan for critical or new-part lots',
    },
    {
      aql_id: 'AQL-RELAX',
      aql_name: 'AQL 1.5/4.0',
      minor: '1.5',
      major: '4.0',
      site_code: 'RYG',
      aql_desc: 'Relaxed plan for low-risk or stable lots',
    },
  ],
  aqlLevels: [
    { aqllevel_id: 'AQLLVL-STD-L1', aql_name: 'AQL 1.0/2.5', severity_name: 'Level I', lot_size_min: 1, lot_size_max: 90 },
    { aqllevel_id: 'AQLLVL-STD-L2', aql_name: 'AQL 1.0/2.5', severity_name: 'Level II', lot_size_min: 91, lot_size_max: 280 },
    { aqllevel_id: 'AQLLVL-STD-L3', aql_name: 'AQL 1.0/2.5', severity_name: 'Level III', lot_size_min: 281, lot_size_max: 1200 },
    { aqllevel_id: 'AQLLVL-STD-SP', aql_name: 'AQL 1.0/2.5', severity_name: 'Special', lot_size_min: 1201, lot_size_max: 3200 },
    { aqllevel_id: 'AQLLVL-TIGHT-L1', aql_name: 'AQL 0.65/1.0', severity_name: 'Level I', lot_size_min: 1, lot_size_max: 50 },
    { aqllevel_id: 'AQLLVL-TIGHT-L2', aql_name: 'AQL 0.65/1.0', severity_name: 'Level II', lot_size_min: 51, lot_size_max: 150 },
    { aqllevel_id: 'AQLLVL-TIGHT-L3', aql_name: 'AQL 0.65/1.0', severity_name: 'Level III', lot_size_min: 151, lot_size_max: 500 },
    { aqllevel_id: 'AQLLVL-TIGHT-SP', aql_name: 'AQL 0.65/1.0', severity_name: 'Special', lot_size_min: 501, lot_size_max: 1200 },
    { aqllevel_id: 'AQLLVL-RELAX-L1', aql_name: 'AQL 1.5/4.0', severity_name: 'Level I', lot_size_min: 1, lot_size_max: 125 },
    { aqllevel_id: 'AQLLVL-RELAX-L2', aql_name: 'AQL 1.5/4.0', severity_name: 'Level II', lot_size_min: 126, lot_size_max: 315 },
    { aqllevel_id: 'AQLLVL-RELAX-L3', aql_name: 'AQL 1.5/4.0', severity_name: 'Level III', lot_size_min: 316, lot_size_max: 1250 },
    { aqllevel_id: 'AQLLVL-RELAX-SP', aql_name: 'AQL 1.5/4.0', severity_name: 'Special', lot_size_min: 1251, lot_size_max: 5000 },
  ],
  aqlLevelClasses: [
    { defectclass_name: 'Critical', samplesize: 13, accept: 0, reject: 1 },
    { defectclass_name: 'Major', samplesize: 20, accept: 1, reject: 2 },
    { defectclass_name: 'Minor', samplesize: 32, accept: 2, reject: 3 },
  ],
};

export const partsCatalogReferenceSeed = {
  partClasses: [
    {
      partclass_id: 'PCLASS-ELEC',
      partclass_name: 'Electronic Components',
      partclass_desc: 'Boards, ICs, connectors, and powered sub-parts',
      site_code: 'BKK',
    },
    {
      partclass_id: 'PCLASS-MECH',
      partclass_name: 'Mechanical Parts',
      partclass_desc: 'Brackets, stamped parts, and machined items',
      site_code: 'CBR',
    },
    {
      partclass_id: 'PCLASS-PLAS',
      partclass_name: 'Plastic Components',
      partclass_desc: 'Molded housings, clips, and covers',
      site_code: 'RYG',
    },
  ],
  partClassCategories: [
    {
      Category_ID: 'PCAT-5M1E',
      Category_name: '5M1E',
      Category_desc: 'Root-cause analysis category bucket',
      partclass_name: 'Electronic Components',
    },
    {
      Category_ID: 'PCAT-INCOMING',
      Category_name: 'Incoming Quality',
      Category_desc: 'Incoming inspection and supplier release controls',
      partclass_name: 'Electronic Components',
    },
    {
      Category_ID: 'PCAT-ASSY',
      Category_name: 'Assembly Readiness',
      Category_desc: 'Assembly preparation and workability controls',
      partclass_name: 'Mechanical Parts',
    },
    {
      Category_ID: 'PCAT-DIM',
      Category_name: 'Dimensional Control',
      Category_desc: 'Dimensional capability and tolerance controls',
      partclass_name: 'Mechanical Parts',
    },
    {
      Category_ID: 'PCAT-COS',
      Category_name: 'Cosmetic Quality',
      Category_desc: 'Appearance and cosmetic acceptance controls',
      partclass_name: 'Plastic Components',
    },
    {
      Category_ID: 'PCAT-PACK',
      Category_name: 'Packing Condition',
      Category_desc: 'Packing, labeling, and shipment readiness controls',
      partclass_name: 'Plastic Components',
    },
  ],
  partTypes: [
    {
      parttype_id: 'PT-CONN',
      parttype_name: 'Connector',
      parttype_code: 'CONN',
      parttype_desc: 'Electrical or signal connector',
    },
    {
      parttype_id: 'PT-BRKT',
      parttype_name: 'Bracket',
      parttype_code: 'BRKT',
      parttype_desc: 'Bracket, shield, or stamped support part',
    },
    {
      parttype_id: 'PT-HSG',
      parttype_name: 'Housing',
      parttype_code: 'HSG',
      parttype_desc: 'Cover, case, or molded housing',
    },
    {
      parttype_id: 'PT-PCB',
      parttype_name: 'PCB Assembly',
      parttype_code: 'PCBA',
      parttype_desc: 'Printed circuit board assembly',
    },
  ],
  parts: [
    {
      part_id: 'PART-ECU-PCBA',
      part_code: 'ECU-PCBA-001',
      part_name: 'ECU Main PCB Assembly',
      part_desc: 'Main ECU printed circuit assembly',
      site_code: 'BKK',
      partclass_name: 'Electronic Components',
      parttype_code: 'PCBA',
      aql_name: 'AQL 0.65/1.0',
      Attribute1: 'Revision A',
      Attribute2: 'Lead-Free',
      Attribute3: null,
      Attribute4: null,
    },
    {
      part_id: 'PART-BRKT-002',
      part_code: 'BRKT-MNT-002',
      part_name: 'Mounting Bracket',
      part_desc: 'Stamped mounting bracket for display assembly',
      site_code: 'CBR',
      partclass_name: 'Mechanical Parts',
      parttype_code: 'BRKT',
      aql_name: 'AQL 1.0/2.5',
      Attribute1: 'Zinc Plated',
      Attribute2: null,
      Attribute3: null,
      Attribute4: null,
    },
    {
      part_id: 'PART-HSG-003',
      part_code: 'HSG-CTRL-003',
      part_name: 'Controller Housing',
      part_desc: 'Injection molded housing for controller assembly',
      site_code: 'RYG',
      partclass_name: 'Plastic Components',
      parttype_code: 'HSG',
      aql_name: 'AQL 1.5/4.0',
      Attribute1: 'Black Texture',
      Attribute2: null,
      Attribute3: null,
      Attribute4: null,
    },
  ],
  partDataCategories: [
    {
      partdatacategory_id: 'PDATA-VOLT',
      partdatacategory_name: 'Voltage Check',
      part_code: 'ECU-PCBA-001',
      minimum: 11.5,
      maximum: 12.5,
      partdatacategory_desc: 'Nominal operating voltage check',
    },
    {
      partdatacategory_id: 'PDATA-CURR',
      partdatacategory_name: 'Current Draw',
      part_code: 'ECU-PCBA-001',
      minimum: 0,
      maximum: 2.5,
      partdatacategory_desc: 'Maximum allowable current draw',
    },
    {
      partdatacategory_id: 'PDATA-TORQ',
      partdatacategory_name: 'Fastening Torque',
      part_code: 'BRKT-MNT-002',
      minimum: 2,
      maximum: 4,
      partdatacategory_desc: 'Recommended fastening torque range',
    },
  ],
  partDimensionCategories: [
    {
      partdimensioncategory_id: 'PDIM-LEN',
      partdimensioncategory_name: 'Overall Length',
      part_code: 'BRKT-MNT-002',
      minimum: 119.5,
      maximum: 120.5,
      partdimensioncategory_desc: 'Overall bracket length',
    },
    {
      partdimensioncategory_id: 'PDIM-WID',
      partdimensioncategory_name: 'Overall Width',
      part_code: 'BRKT-MNT-002',
      minimum: 39.8,
      maximum: 40.2,
      partdimensioncategory_desc: 'Overall bracket width',
    },
    {
      partdimensioncategory_id: 'PDIM-WALL',
      partdimensioncategory_name: 'Wall Thickness',
      part_code: 'HSG-CTRL-003',
      minimum: 1.8,
      maximum: 2.2,
      partdimensioncategory_desc: 'Nominal housing wall thickness',
    },
  ],
  partNoiseCategories: [
    {
      partnoisecategory_id: 'PNOISE-RATTLE',
      partnoisecategory_name: 'Rattle Check',
      part_code: 'HSG-CTRL-003',
      minimum: 0,
      maximum: 30,
      partnoisecategory_desc: 'Maximum acceptable rattle level in dB',
    },
    {
      partnoisecategory_id: 'PNOISE-BUZZ',
      partnoisecategory_name: 'Buzz Check',
      part_code: 'ECU-PCBA-001',
      minimum: 0,
      maximum: 25,
      partnoisecategory_desc: 'Maximum acceptable buzz level in dB',
    },
  ],
};

export const auditReferenceSeed = {
  categories: [
    {
      audit_category_id: 'AUDCAT-SYSTEM',
      audit_category_name: 'System Audit',
      audit_category_code: 'SYS',
      audit_category_desc: 'QMS system and process governance audit',
      with_rating: 1,
      with_auditees: 1,
      with_auditors: 1,
      with_attendees: 1,
      with_audit_plan: 1,
    },
    {
      audit_category_id: 'AUDCAT-SUPPLIER',
      audit_category_name: 'Supplier Audit',
      audit_category_code: 'SUP',
      audit_category_desc: 'Supplier process and quality capability audit',
      with_rating: 1,
      with_auditees: 1,
      with_auditors: 1,
      with_attendees: 0,
      with_audit_plan: 1,
    },
    {
      audit_category_id: 'AUDCAT-PROCESS',
      audit_category_name: 'Process Audit',
      audit_category_code: 'PRC',
      audit_category_desc: 'Line and work-instruction adherence audit',
      with_rating: 1,
      with_auditees: 1,
      with_auditors: 1,
      with_attendees: 1,
      with_audit_plan: 1,
    },
  ],
  types: [
    {
      audit_type_id: 'AUDTYPE-ISO9001',
      audit_type_name: 'ISO 9001 Audit',
      audit_type_desc: 'Quality management system compliance audit',
      audit_category_code: 'SYS',
    },
    {
      audit_type_id: 'AUDTYPE-IATF',
      audit_type_name: 'IATF 16949 Audit',
      audit_type_desc: 'Automotive QMS compliance audit',
      audit_category_code: 'SYS',
    },
    {
      audit_type_id: 'AUDTYPE-LPA',
      audit_type_name: 'Layered Process Audit',
      audit_type_desc: 'Routine layered process discipline audit',
      audit_category_code: 'PRC',
    },
    {
      audit_type_id: 'AUDTYPE-SUPP',
      audit_type_name: 'Supplier Assessment',
      audit_type_desc: 'Supplier capability and readiness assessment',
      audit_category_code: 'SUP',
    },
  ],
  criterias: [
    {
      criteria_id: 'CRIT-QMS',
      criteria_name: 'Quality Management',
      criteria_desc: 'Quality system ownership and deployment',
    },
    {
      criteria_id: 'CRIT-PROCESS',
      criteria_name: 'Process Control',
      criteria_desc: 'Process stability, controls, and reaction plan',
    },
    {
      criteria_id: 'CRIT-TRACE',
      criteria_name: 'Traceability',
      criteria_desc: 'Lot traceability and record completeness',
    },
    {
      criteria_id: 'CRIT-CAPA',
      criteria_name: 'Corrective Action',
      criteria_desc: 'Containment, cause, and corrective action quality',
    },
  ],
};

export const secondaryMaintenanceReferenceSeed = {
  supplierInformation: [
    {
      supplier_information_id: 'SINFO-ALPHA-QA',
      supplier_name: 'Alpha Electronics Co.',
      first_name: 'Anita',
      middle_name: '',
      last_name: 'Chaiwat',
      supplier_information_desc: 'Primary quality contact for PCB assembly',
      attachment_id: '',
      attachment_name: '',
      attachment_extension: '',
    },
    {
      supplier_information_id: 'SINFO-BETA-SQE',
      supplier_name: 'Beta Plastics Ltd.',
      first_name: 'Pravit',
      middle_name: '',
      last_name: 'Kongsri',
      supplier_information_desc: 'Supplier quality and mold maintenance contact',
      attachment_id: '',
      attachment_name: '',
      attachment_extension: '',
    },
    {
      supplier_information_id: 'SINFO-GAMMA-OPS',
      supplier_name: 'Gamma Metal Works',
      first_name: 'Mina',
      middle_name: '',
      last_name: 'Tan',
      supplier_information_desc: 'Operations and stamping quality contact',
      attachment_id: '',
      attachment_name: '',
      attachment_extension: '',
    },
  ],
  certifications: [
    {
      certification_id: 'CERT-ISO9001',
      certification_name: 'ISO 9001:2015',
      certification_desc: 'Quality management system certification',
    },
    {
      certification_id: 'CERT-IATF',
      certification_name: 'IATF 16949:2016',
      certification_desc: 'Automotive quality management certification',
    },
    {
      certification_id: 'CERT-ISO14001',
      certification_name: 'ISO 14001:2015',
      certification_desc: 'Environmental management certification',
    },
    {
      certification_id: 'CERT-VDA63',
      certification_name: 'VDA 6.3',
      certification_desc: 'Automotive process audit competency',
    },
  ],
  groups: [
    {
      group_id: 'GRP-QA',
      group_name: 'Quality Assurance',
      group_desc: 'Incoming, in-process, and outgoing quality team',
    },
    {
      group_id: 'GRP-SQE',
      group_name: 'Supplier Quality',
      group_desc: 'Supplier development and supplier quality engineering',
    },
    {
      group_id: 'GRP-ENG',
      group_name: 'Engineering',
      group_desc: 'Product, process, and sustaining engineering',
    },
    {
      group_id: 'GRP-LAB',
      group_name: 'Testing Laboratory',
      group_desc: 'Reliability, calibration, and validation lab group',
    },
  ],
  trainingPrograms: [
    {
      training_program_id: 'TRN-RCA',
      training_program_name: 'Root Cause Analysis',
      training_program_desc: '5M1E, 5 Why, and containment decision training',
    },
    {
      training_program_id: 'TRN-SPC',
      training_program_name: 'SPC Fundamentals',
      training_program_desc: 'Statistical process control basics and reaction plans',
    },
    {
      training_program_id: 'TRN-AUDIT',
      training_program_name: 'Internal Audit',
      training_program_desc: 'Audit planning, execution, and evidence review',
    },
    {
      training_program_id: 'TRN-APQP',
      training_program_name: 'APQP and PPAP',
      training_program_desc: 'Product launch quality planning and PPAP fundamentals',
    },
  ],
  faqItems: [
    {
      faq_item_id: 'FAQ-MNR-NEW',
      faq_category: 1,
      question: 'How do I submit a new MNR?',
      answer: 'Open the MNR workflow, create a new record, attach evidence, and route it for review.',
      sequence: 1,
      faq_item_desc: 'MNR workflow quick guide',
    },
    {
      faq_item_id: 'FAQ-AQL',
      faq_category: 2,
      question: 'What does AQL mean?',
      answer: 'AQL means Acceptable Quality Level and defines the sampling acceptance criteria for a lot.',
      sequence: 2,
      faq_item_desc: 'Quality terminology',
    },
    {
      faq_item_id: 'FAQ-5M1E',
      faq_category: 2,
      question: 'What is 5M1E analysis used for?',
      answer: '5M1E helps structure root-cause analysis around Man, Machine, Material, Method, Measurement, and Environment.',
      sequence: 3,
      faq_item_desc: 'Root-cause analysis reference',
    },
    {
      faq_item_id: 'FAQ-AUDIT',
      faq_category: 3,
      question: 'How do I prepare for an audit plan review?',
      answer: 'Confirm the audit scope, checklist, attendees, and required records before release.',
      sequence: 4,
      faq_item_desc: 'Audit planning reference',
    },
  ],
  messageInfo: [
    {
      messageinfo_id: 'MSG-QUALITY-ALERT',
      key_name: 'Quality Alert',
      value: 'Escalate any critical defect immediately to the assigned quality lead.',
    },
    {
      messageinfo_id: 'MSG-AUDIT-REMINDER',
      key_name: 'Audit Reminder',
      value: 'Audit evidence and attendance lists must be complete before closure.',
    },
    {
      messageinfo_id: 'MSG-TRAINING',
      key_name: 'Training Reminder',
      value: 'Review required training completion before approving role-related readiness.',
    },
    {
      messageinfo_id: 'MSG-MAINTENANCE',
      key_name: 'Maintenance Notice',
      value: 'Master-data changes should be reviewed for downstream workflow impact before release.',
    },
  ],
  customers: [
    {
      customer_id: 'CUST-SAMSUNG',
      customer_name: 'Samsung Electronics',
      customer_desc: 'Consumer electronics and display components customer',
    },
    {
      customer_id: 'CUST-TOYOTA',
      customer_name: 'Toyota Motor Corporation',
      customer_desc: 'Automotive OEM — ECU and sensor module customer',
    },
    {
      customer_id: 'CUST-HONDA',
      customer_name: 'Honda Motor Co.',
      customer_desc: 'Automotive OEM — display assembly and bracket customer',
    },
    {
      customer_id: 'CUST-BOSCH',
      customer_name: 'Robert Bosch GmbH',
      customer_desc: 'Tier-1 automotive supplier and electronics partner',
    },
  ],
  newsItems: [
    {
      news_id: 'NEWS-SQMP-LIVE',
      news_name: 'SQMP Workflow Go-Live',
      news_desc: 'The SQMP plan creation, approval, issuance, and response workflow is now available for all sites.',
      file_id: '',
      file_name: '',
      file_extension: '',
      sequence: 1,
    },
    {
      news_id: 'NEWS-QMQA-SCHEDULE',
      news_name: 'QMQA Audit Schedule Q2 2026',
      news_desc: 'Quarterly QMQA audit schedule has been published. Review assigned audits in the QMQA calendar.',
      file_id: '',
      file_name: '',
      file_extension: '',
      sequence: 2,
    },
    {
      news_id: 'NEWS-SUPPLIER-PORTAL',
      news_name: 'Supplier Portal Updates',
      news_desc: 'Supplier information and contact management has been updated. Suppliers can now receive automated notification emails.',
      file_id: '',
      file_name: '',
      file_extension: '',
      sequence: 3,
    },
    {
      news_id: 'NEWS-5M1E-RELEASE',
      news_name: '5M1E Release Process Streamlined',
      news_desc: '5M1E evaluation, approval, and release workflow now supports parallel checker and approver routing.',
      file_id: '',
      file_name: '',
      file_extension: '',
      sequence: 4,
    },
  ],
};
