export enum WorkflowStatusEnum {
  DRAFT = 'DRAFT',
  NEW = 'NEW',
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  // Evaluation / Technical Phases
  FAPPROVED = 'FAPPROVED',
  EVALUATION = 'EVALUATION',
  CHECKED = 'CHECKED', // Two-stage approval: Checker reviewed, awaiting Approver
  APPROVED = 'APPROVED',
  APPROVED_WC = 'APPROVED_WC',
  APPROVEDWC = 'APPROVEDWC',
  REJECTED = 'REJECTED',
  RAR = 'RAR',
  ISSUED = 'ISSUED',
  FR = 'FR',
  IR = 'IR',
  REPORT = 'REPORT',
  RESPONSE_AWAITING = 'RESPONSE_AWAITING',
  RESPONSE_AWAIT_APPROVAL = 'RESPONSE_AWAIT_APPROVAL',
  RESPONSE_RECEIVED = 'RESPONSE_RECEIVED',
  RREJECTED = 'RREJECTED',
  RELEASE = 'RELEASE',
  HOLD = 'HOLD',
  CANCEL = 'CANCEL',
  CLOSED = 'CLOSED'
}
